# Prometheus configuration for Teder Trading Bot monitoring

global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

# Rule files
rule_files:
  - "alert_rules.yml"

# Scraping configurations
scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s
    metrics_path: '/metrics'

  # Node Exporter for system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['monitoring:9100']
    scrape_interval: 15s
    scrape_timeout: 10s

  # Docker container metrics
  - job_name: 'docker'
    static_configs:
      - targets: ['docker-host:9323']
    scrape_interval: 30s
    
  # Trading bot application metrics (if implemented)
  - job_name: 'teder-bot'
    static_configs:
      - targets: ['teder-bot:8080']
    scrape_interval: 30s
    metrics_path: '/metrics'
    scrape_timeout: 10s
    
  # Redis metrics (if using Redis exporter)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 30s

# Alerting configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Remote write configuration (optional - for long-term storage)
# remote_write:
#   - url: "http://remote-storage:8428/api/v1/write"
#     queue_config:
#       max_samples_per_send: 1000
#       max_shards: 10
#       capacity: 10000

# Storage configuration
storage:
  tsdb:
    path: /prometheus
    retention.time: 7d
    retention.size: 1GB